--날짜 함수

SELECT SYSDATE FROM DUAL -- 현재시간

-- TO_CHAR : 시간을 원하는 문자포맷으로
-- TO_DATE : 문자를 시간포맷으로

SELECT SYSDATE, TO_CHAR(SYSDATE, 'YY-MM-DD') FROM DUAL

SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS') FROM DUAL
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL
TO_DATE('2026-09-28', 'YYYY-MM-DD')

--HIREDATE를 YY-MM-DD
SELECT TO_CHAR(HIREDATE, 'YY-MM-DD')AS 입사일 FROM PROFESSOR
WHERE TO_CHAR(HIREEDATE, 'YY') = '85'
