-- 조인
-- STUDENT 테이블의 STU_NO는 PK(유니크 + NOT NULL)
SELECT * FROM STUDENT

--ENROL 테이블의 STU_NO는 FK(STUDENT 테이블의 STU_NO를 참조하는 참조 키)
SELECT * FROM ENROL

--조인의 종류는 여러개(INNERM OUTER-LEFT OR RIGHT, CROSS 기타 등등)
--INNER 조인 위주로 시작

--(학번, 이름 ,학과) -> STUDENT, (점수) -> ENROL

SELECT 
    S.STU_NO, STU_NAME, STU_DEPT , ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO -- ON 뒤에 조인 조건

-- 시험점수 평균
SELECT 
    S.STU_NO, STU_NAME, STU_DEPT , AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT

--각 과목별 점수
SELECT * FROM ENROL;

SELECT * FROM SUBJECT

SELECT * FROM SUBJECT S
INNER JOIN ENROL E ON S.SUB_NO = E.SUB_NO 

--(학번, 이름 ,학과) -> STUDENT, (점수) -> ENROL, (과목명) -> SUBJECT

SELECT 
    S.STU_NO, STU_NAME, STU_DEPT , ENR_GRADE, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO -- ON 뒤에 조인 조건
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
ORDER BY S.STU_NO

--학과(STUDENT)별 시험(ENROL) 평균점수 출력

SELECT 
     STU_DEPT,
     AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT

SELECT * FROM EMP
SELECT * FROM DEPT

--사번 ->EMP, 이름 ->EMP, 부서번호->양쪽에 있다 ,부서이름->DEPT, 출력

SELECT
    EMPNO, ENAME, D.DEPTNO, DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO

--SALGRADE
SELECT * FROM SALGRADE

--조인은 꼭 값이 같은 컬럼끼리 하는건 아니다
--사원들의 급여 등급 출력(사번,이름, 급여, 급여등급 출력)
SELECT 
    EMPNO, ENAME, SAL, GRADE
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL

--각 부서별(DEPT - DNAME) 급여 평균 등급 출력
--(부서번호, 부서이름, 급여 등급 출력)
SELECT
    E.DEPTNO, DNAME,
    AVG(GRADE)
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL 
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY  E.DEPTNO, DNAME

-- STUDENT, ENROL, SUBJECT
-- 1. 과목별 평균 점수 출력 (출력 : 과목이름, 평균점수)
SELECT * FROM STUDENT 
SELECT * FROM ENROL
SELECT * FROM SUBJECT

SELECT SUB_NAME,
       AVG(ENR_GRADE)
FROM ENROL E
INNER JOIN SUBJECT S ON E.SUB_NO = S.SUB_NO
GROUP BY SUB_NAME

-- 2. 학생별 시험 평균 점수 출력. 단 평균 60점 이상만(출력 : 학번, 이름, 평균점수)
SELECT E.STU_NO, STU_NAME, AVG(ENR_GRADE)  
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY E.STU_NO, STU_NAME
HAVING AVG(ENR_GRADE) > 60

-- 3. 2개이상의 시험을 본 학생들의 이름, 시험개수 출력
SELECT *
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO

-- 4. '강종영' 교수의 수업을 들은(시험을 본) 학생의 학번, 이름, 학과, 시험점수 출력

SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE  
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO 
WHERE SUB.SUB_NO = '101'


-- EMP, DEPT, SALGRADE
-- 5. 급여 등급이 3이상인 사람의 사번, 이름, 급여등급 출력

SELECT 
    EMPNO, ENAME, SAL, GRADE
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
WHERE GRADE > 3
-- 6. 직급(JOB) 평균 급여 등급이 3이상인 직급, 급여등급 출력

SELECT * FROM EMP

SELECT 
    JOB, AVG(SAL), GRADE
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
WHERE GRADE > 3
GROUP BY JOB , GRADE 

-- 7. 직급별 평균 급여 등급이 3이상인 사람의 수 출력(직급, 3등급 이상 사람 수)
SELECT 
     COUNT(*)
FROM EMP E 
INNER JOIN SALGRADE S ON E.SAL BETWEEN LOSAL AND HISAL
WHERE GRADE > 3
 

-- 8. 부서별 평균 급여 출력. 단, 1800 이상인 부서만.(출력 : 부서번호, 부서이름, 평균 급여)
SELECT * FROM DEPT
SELECT * FROM EMP


SELECT * 
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO   
WHERE AVG(SAL) > 1800

